### ISSUE TITLE
error: Unknown subcommand: get-url

### ISSUE THREAD

**Issue by eserte** [oalders/git-helpers#4]
Older git versions (e.g. the one which comes with Debian/jessie) cannot handle `git remote get-url ...`, so `travis-open` does not work:
```
$ travis-open
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
...
```
An alternative for older git would be something like `git config remote.origin.url`.

**Comment by oalders** [comment]
Thanks for this as well @eserte!
